include: package:flutter_lints/flutter.yaml
analyzer:
  exclude: [build/**]
linter:
  rules:
    avoid_print: true
    omit_local_variable_types: true
    use_key_in_widget_constructors: true
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    prefer_mixin: true
    prefer_single_quotes: true
    Missing_required_param: true